# Generated by Django 3.0.6 on 2020-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_auto_20200626_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='t', max_length=250),
        ),
    ]
