# Generated by Django 3.0.6 on 2020-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_auto_20201030_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='w', max_length=250),
        ),
    ]
