# Generated by Django 3.0.6 on 2020-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_auto_20201031_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='v', max_length=250),
        ),
    ]
