# Generated by Django 3.0.6 on 2020-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0009_auto_20201105_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='h', max_length=250),
        ),
    ]
