# Generated by Django 3.0.6 on 2020-11-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_auto_20201107_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='j', max_length=250),
        ),
    ]
