# Generated by Django 3.0.6 on 2020-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0014_auto_20201126_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='g', max_length=250),
        ),
    ]
