# Generated by Django 3.0.6 on 2020-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0015_auto_20201126_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='o', max_length=250),
        ),
    ]
