# Generated by Django 3.0.6 on 2020-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0016_auto_20201127_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='e', max_length=250),
        ),
    ]
