# Generated by Django 3.0.6 on 2020-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0017_auto_20201127_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='w', max_length=250),
        ),
    ]
