# Generated by Django 3.0.6 on 2020-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0018_auto_20201207_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='l', max_length=250),
        ),
    ]
