# Generated by Django 3.0.6 on 2020-10-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=8, max_digits=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed')], default='active', max_length=200)),
                ('week', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_paid', models.DecimalField(decimal_places=8, max_digits=50)),
                ('percentage', models.DecimalField(decimal_places=8, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
