# Generated by Django 3.0.6 on 2020-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='tx_hash',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
