# Generated by Django 3.0.6 on 2020-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investments_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='investments',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='investments',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
