# Generated by Django 3.0.6 on 2020-12-07 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='john', max_length=200)),
                ('email', models.CharField(default='john', max_length=200)),
                ('message', models.TextField(default='john', max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('i_d', models.CharField(default='01f8e6cbdb', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='john', max_length=200)),
                ('email', models.CharField(default='john', max_length=200)),
                ('inquiry', models.TextField(default='john', max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('i_d', models.CharField(default='436739f124', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(default='e0184831b4', max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Unresolved', 'Unresolved'), ('Resolved', 'Resolved')], default='Unresolved', max_length=200)),
                ('category', models.CharField(default='none', max_length=200)),
                ('title', models.CharField(default='none', max_length=200)),
                ('description', models.TextField(default='none', max_length=200)),
                ('chat', models.TextField(default='{}', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
