# Generated by Django 3.0.6 on 2020-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200705_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='first_name',
            field=models.CharField(default='john', max_length=200),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='last_name',
            field=models.CharField(default='doe', max_length=200),
        ),
    ]
