# Generated by Django 3.0.6 on 2020-11-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='data_type',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
